### ISSUE TITLE
View Ratings "Did You Mean....?" Functionality

### ISSUE THREAD

**Issue by Tyler-Lopez** [CompSci-Discord-Bot/CompSci-Discord-Bot#104]
When a user types an incorrect professor name, determine how close their input was to an actual professor's name - then present a "Did you mean?" option.

Ex: 
USER: !viewratings mannicam
BOT: Professor not found. Did you mean maniccam? (Thumbs up, thumbs down emoji)
On thumbs up -> post Maniccam reviews

**Comment by Tyler-Lopez** [comment]
Changed plan to now not include emoji user-input listening: in most cases they will have meant the suggested professor and this prevents users not understanding they must thumbs-up.

**Comment by bdk99** [comment]
I like your thoughts on this.. I will take a closer look and review this tomorrow.  I appreciate your time and energy spent on this.  You are welcome to continue making improvements, or be done if you'd like.. Totally up to you.  If you have questions on other issues or things to do please feel free to ask anytime.
