### ISSUE TITLE
Fix Quote Search Command

### ISSUE THREAD

**Issue by bdk99** [CompSci-Discord-Bot/CompSci-Discord-Bot#27]
Fix Quote Search Command

Possibly add cronjob bot restarting with the provider... Unsure how to do this.  Research required.

https://stackoverflow.com/questions/33546880/node-js-how-to-reload-module

**Comment by bdk99** [comment]
Attempted once, but I was unsuccessful

**Comment by Nanosplitter** [comment]
Fixed in PR #47
