### ISSUE TITLE
Fix bot crashes on !quotelist command (main bot)

### ISSUE THREAD

**Issue by bdk99** [CompSci-Discord-Bot/CompSci-Discord-Bot#55]

**Comment by Nanosplitter** [comment]
tempQuotesList.txt needs to be in the root (At the same level as index.js, but my git won't let me add it and push it. So if @bdk99 adds it, it should be all fixed. The server filesystem seems to not let code add files, but will let the code write to an already-existing file, and the tempQuotesList.txt is not already an existing file.

**Comment by bdk99** [comment]
Reassigned to @Nanosplitter

**Comment by bdk99** [comment]
Another alternative that Colin suggested to me was to just send the quotes list command as a message instead of a text file... My only problem with this is that it pings everyone that was tagged in each quote in that single search message.  So in summary, people would have the ability to randomly ping spam without the ability to stop it (since its with the bot).
