### ISSUE TITLE
Fix ratep command bugs and small improvements

### ISSUE THREAD

**Issue by bdk99** [CompSci-Discord-Bot/CompSci-Discord-Bot#81]
Fix bugs with the ratep command

--Do not allow people to submit reviews with empty content
--If a professor does not exist.. Give an admin or mod the ability to add them on the spot... instead of adding the name to the list and creating a new text file for the purpose.

**Comment by Tyler-Lopez** [comment]
Pull request does not yet address adding professors on the spot.

Suggested addition is to possibly, on a completely unsuccessful rate or view search, send a thumbs down thumbs up post to some review channel.
